### ISSUE TITLE
Using Guice Named components in Spring when using the PartiallyRefreshableApplicationContext

### ISSUE THREAD

**Issue by swatro** [spring-projects/spring-guice#102]
I have a Named Guice component coming from a Guice Module. I then have a Spring component which autowires in the Named Guice component using a qualifier. The Spring component is added to the Guice context using a SpringModule. We are using a BeanFactoryProvider to create the Spring module which should allow layering of Spring and Guice components. 

From looking at the library code, I believe this is not currently possible. I think code would need to be added [here](https://github.com/spring-projects/spring-guice/blob/master/src/main/java/org/springframework/guice/module/GuiceAutowireCandidateResolver.java#L120) in order to make this work. 

Thoughts? Am I missing something to make this work?

See example below: 
```
public class GuiceInSpringInGuiceTests {

    @Test
    void shouldResolveNamedComponentsInSpring() {
        Class<?>[] components = new Class<?>[]{ BananaBreakfast.class };
        BeanFactoryProvider beanFactoryProvider = BeanFactoryProvider.from(components);
        SpringModule module = new SpringModule(beanFactoryProvider);

        Injector injector = Guice.createInjector(module, new BreakfastModule());

        BananaBreakfast bananaBreakfast = injector.getInstance(BananaBreakfast.class);
        assertThat(bananaBreakfast.getFavorite()).isEqualTo("banana");
    }

    @Component
    public static class BananaBreakfast {

        private final BananaPancake pancake;

        @Autowired
        public BananaBreakfast(@Qualifier("banana") BananaPancake bananaPancakeProvider) {
            this.pancake = bananaPancakeProvider;
        }

        public String getFavorite() {
            return pancake.favoritePancake();
        }
        
    }

    public static class BreakfastModule extends AbstractModule {
        
        @Provides
        @Singleton
        @Named("banana")
        public BananaPancake bananaPancakeProvider() {
            return new BananaPancake("banana");
        }

    }
    
    public static class BananaPancake {

        private final String favoritePancake;

        public BananaPancake(String favoritePancake) {
            this.favoritePancake = favoritePancake;
        }

        public String favoritePancake() {
            return favoritePancake;
        }
    }
}

```

Running the above test results in the following error: 

```
com.google.inject.ConfigurationException: Guice configuration errors:

1) [Guice/MissingConstructor]: No injectable constructor for type GuiceInSpringInGuiceTests$BananaPancake.

class GuiceInSpringInGuiceTests$BananaPancake does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : GuiceInSpringInGuiceTests$BananaPancake.class(GuiceInSpringInGuiceTests.java:62)
     while locating GuiceInSpringInGuiceTests$BananaPancake

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
GuiceInSpringInGuiceTests$BananaPancake: "org.springframework.guice.GuiceInSpringInGuiceTests$BananaPancake"
========================
End of classname legend:
========================


	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1127)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1134)
	at org.springframework.guice.module.GuiceAutowireCandidateResolver$1.getTarget(GuiceAutowireCandidateResolver.java:131)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:676)
	at org.springframework.guice.GuiceInSpringInGuiceTests$BananaPancake$$EnhancerBySpringCGLIB$$667ef2d5.favoritePancake(<generated>)
	at org.springframework.guice.GuiceInSpringInGuiceTests$BananaBreakfast.getFavorite(GuiceInSpringInGuiceTests.java:42)
	at org.springframework.guice.GuiceInSpringInGuiceTests.shouldResolveNamedComponentsInSpring(GuiceInSpringInGuiceTests.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by dsyer** [comment]
Fixed in #103
