### ISSUE TITLE
org.springframework.context.ApplicationListener<T> cannot be used as a key; It is not fully specified

### ISSUE THREAD

**Issue by agoel2** [spring-projects/spring-guice#26]
From your example of using existing Guice Modules in a Spring ApplicationContext
```
@EnableGuiceModules
@Configuration
public static class TestConfig extends AbstractModule {
    @Bean
    public MyModule myModule() {
        return new MyModule();
    }
    @Bean
    public Spam spam(Service service) {
        return new Spam(service);
    }

}
```

I get the following error

org.springframework.context.ApplicationListener<T> cannot be used as a key; It is not fully specified

at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:?]

**Comment by agoel2** [comment]
@dsyer are you able to help please

**Comment by dsyer** [comment]
Do you have a complete sample to share?

**Comment by agoel2** [comment]
Its literally just this. My intention is to be able to try and use guice bound beans from a jar in our spring application. As soon as I put in the Configuration and EnableGuiceModules annotations and start the server , I get that exception 
```
@EnableGuiceModules
@Configuration
public class CybsPaymentHybrisModule extends AbstractModule
{
    @Override
    protected void configure()
    {
        //do something
    }
}
```

Full Stacktrace

com.google.inject.CreationException: Unable to create injector, see the following errors:

1) org.springframework.context.ApplicationListener<T> cannot be used as a key; It is not fully specified.

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.1.0.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
	at org.springframework.guice.annotation.ModuleRegistryConfiguration.createInjector(ModuleRegistryConfiguration.java:53) ~[spring-guice-1.0.0.RELEASE.jar:?]
	at org.springframework.guice.annotation.ModuleRegistryConfiguration.postProcessBeanDefinitionRegistry(ModuleRegistryConfiguration.java:123) ~[spring-guice-1.0.0.RELEASE.jar:?]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:123) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at de.hybris.platform.core.HybrisContextFactory.refreshContext(HybrisContextFactory.java:95) [coreserver.jar:?]
	at de.hybris.platform.core.HybrisContextFactory$ApplicationContextFactory.build(HybrisContextFactory.java:263) [coreserver.jar:?]
	at de.hybris.platform.core.HybrisContextHolder.getApplicationInstance(HybrisContextHolder.java:87) [coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.createCoreApplicationContext(AbstractTenant.java:752) [coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.doStartupSafe(AbstractTenant.java:790) [coreserver.jar:?]
	at de.hybris.platform.core.AbstractTenant.doStartUp(AbstractTenant.java:724) [coreserver.jar:?]
	at de.hybris.platform.core.Registry.assureTenantStarted(Registry.java:648) [coreserver.jar:?]
	at de.hybris.platform.core.Registry.activateTenant(Registry.java:709) [coreserver.jar:?]
	at de.hybris.platform.core.Registry.setCurrentTenant(Registry.java:553) [coreserver.jar:?]
	at de.hybris.platform.core.Registry.activateMasterTenant(Registry.java:616) [coreserver.jar:?]
	at de.hybris.platform.core.Registry.startup(Registry.java:431) [coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.startRegistry(HybrisContextLoaderListener.java:265) [coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.doInitWebApplicationContext(HybrisContextLoaderListener.java:153) [coreserver.jar:?]
	at de.hybris.platform.spring.HybrisContextLoaderListener.initWebApplicationContext(HybrisContextLoaderListener.java:143) [coreserver.jar:?]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at de.hybris.platform.spring.HybrisContextLoaderListener.contextInitialized(HybrisContextLoaderListener.java:79) [coreserver.jar:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524) [catalina.jar:7.0.59]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565) [catalina.jar:7.0.59]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by dsyer** [comment]
Maybe try making the module a `@Bean` instead (as suggested in #22)?

**Comment by dsyer** [comment]
There's a test that is green (see above). If you have one that fails please post a full sample.

**Comment by agoel2** [comment]
I tried making the module @Bean too , but it didn't help.
As soon as I put in the @Configuration annotation , server start up gives me that error.

```
@EnableGuiceModules
@Configuration
public class CybsPaymentHybrisModule
{
    @Bean
    protected CybsPaymentModule myModule()
    {
        return new CybsPaymentModule();
    }

}
```

**Comment by dsyer** [comment]
If you can post a full sample we can analyze it. The snippets you posted so far look identical to tests that pass.

**Comment by tcellucci** [comment]
I have a clean example of the 'not fully specified' issue:
```
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.guice.annotation.EnableGuiceModules;
import org.springframework.guice.annotation.GuiceModule;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = GuiceBridgeTest.SomeSpringConfiguration.class)
public class GuiceBridgeTest {
    /**
     * an generic interface
     *
     * @param <T>
     */
    public interface Foo<T> {
        T getValue();
    }

    /**
     * parameterized implementor of a generic interface Foo<T>
     *
     * @param <T>
     */
    public static class FooImpl<T> implements Foo<T> {
        private final T payload;

        FooImpl(T payload) {
            this.payload = payload;
        }

        @Override
        public T getValue() {
            return payload;
        }
    }

    /**
     * Spring configuration that creates a guice module
     *
     */
    @Configuration
    @EnableGuiceModules
    @GuiceModule
    static class SomeSpringConfiguration {
        /**
         * a fully-specified bean of type FooImpl<String>
         * @return
         */
        @Bean
        public FooImpl<String> fooBean() {
            return new FooImpl<>("foo.foo.foo");
        }
    }

    /**
     * this test will fail prior to startup due to CreationException;
     * reason '[...] cannot be used as a key; It is not fully specified'
     */
    @Test
    public void testBinding() {
        Assert.assertNotNull(this);
    }
}
```

**Comment by tcellucci** [comment]
the underlying cause seems to be in SpringModule.bind(), which is working with BeanFactory.getType().  Since that method returns only the raw class rather than a ResolvableType, SpringModule's attempt to create a binding for each of bean type's generic interfaces is not going to work.  More concretely in the example above, SpringModule will attempt to bind the FooImpl bean with a generic interface type of Foo<T> rather than Foo<String> since it has no type variable info for the bean.

**Comment by dsyer** [comment]
I don't know if that fix is completely general (we can't deal with multiple beans of the same type but with different type parameters, for instance), but your test passes now (as do all the others).

**Comment by agoel2** [comment]
Thank you for the fix. Can you please let us know when would this be released ?

**Comment by dsyer** [comment]
1.1.0.RELEASE is available now (or via snapshots). I had to bump the versions because we are using JDK8 APIs.

**Comment by dsyer** [comment]
http://repo1.maven.org/maven2/org/springframework/guice/spring-guice/1.1.0.RELEASE/
