### ISSUE TITLE
Set multibinder autowiring not working

### ISSUE THREAD

**Issue by rrajendran** [spring-projects/spring-guice#65]
I am trying to Autowire Multiset binder from guice with below example. Any help would be helpful.. thanks

**Car.java**
```
public interface Car {

    public String getModel();
}
```

**Audi.java**

```
public class Audi implements Car {
    @Override
    public String getModel() {
        return "Audi A4";
    }
}
```

**Benz.java**
```
public class Benz implements Car{
    @Override
    public String getModel() {
        return "C 220";
    }
}
```

**AutomobileModule.java**
```
public class AutomobileModule extends AbstractModule {

    @Override
    protected void configure() {
        Multibinder<Car> uriBinder = Multibinder.newSetBinder(binder(), Car.class);
        uriBinder.addBinding().to(Audi.class);
        uriBinder.addBinding().to(Benz.class);
    }
}
```

**SpringGuiceConfig.java**

```
@Configuration
@EnableGuiceModules
@EnableCaching
public class SpringGuiceConfig {

    @Bean
    public Module module() {
        return new AbstractModule() {
            @Override
            protected void configure() {         
                install(new AutomobileModule());
            }
        };
    }
}
```

**Tests**
```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = Application.class)
public class SpringGuiceModuleTest {
    @Autowired
    private Benz car;

    @Test
    public void testSpringGuiceModule(){
        assertThat(car, is(notNullValue()));
    }
}
```

Running above tests getting below. 
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'com.google.inject.internal.Element_com.spring.example.print.document.modules.Car' defined in com.spring.example.print.document.modules.AutomobileModule.configure(AutomobileModule.java:16): Cannot register bean definition [Root bean: class [org.springframework.guice.annotation.GuiceFactoryBean]; scope=prototype; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in com.spring.example.print.document.modules.AutomobileModule.configure(AutomobileModule.java:16)] for bean 'com.google.inject.internal.Element_com.spring.example.print.document.modules.Car': There is already [Root bean: class [org.springframework.guice.annotation.GuiceFactoryBean]; scope=prototype; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in com.spring.example.print.document.modules.AutomobileModule.configure(AutomobileModule.java:17)] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:893)
	at org.springframework.guice.annotation.ModuleRegistryConfiguration.mapBindings(ModuleRegistryConfiguration.java:149)
	at org.springframework.guice.annotation.ModuleRegistryConfiguration.postProcessBeanDefinitionRegistry(ModuleRegistryConfiguration.java:210)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:119)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 24 more
```

**Comment by twicksell** [comment]
Thanks for the test case. I see whats happening here in that the name we generate for the bean doesn't use the concrete class, but only the interface and its qualifiers. Since you don't have any qualifiers set, and you're using the newer versions of Spring which disallow bean overriding by default, you'll hit this error. You could consider setting the property `spring.main.allow-bean-definition-overriding=true` if you need an immediate workaround. I'll see if I can come up with a better fix in the meanwhile.

**Comment by rrajendran** [comment]
**Step1**
After adding the above property, got the below error for missing 

`No implementation for javax.xml.parsers.DocumentBuilderFactory was bound.`

```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.camel.spring.boot.CamelSpringBootInitializationException: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for javax.xml.parsers.DocumentBuilderFactory was bound.
  while locating javax.xml.parsers.DocumentBuilderFactory

1 error
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:269)
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:57)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:119)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 24 more
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for javax.xml.parsers.DocumentBuilderFactory was bound.
  while locating javax.xml.parsers.DocumentBuilderFactory

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1081)
	at org.springframework.guice.module.GuiceAutowireCandidateResolver$1.getTarget(GuiceAutowireCandidateResolver.java:96)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
	at $javax.xml.parsers.DocumentBuilderFactory$$EnhancerBySpringCGLIB$$d50e18ca.newDocumentBuilder(<generated>)
	at org.apache.camel.converter.jaxp.XmlConverter.createDocumentBuilder(XmlConverter.java:1178)
	at org.apache.camel.converter.jaxp.XmlConverter.toDOMDocument(XmlConverter.java:874)
	at org.apache.camel.model.ModelHelper.loadRoutesDefinition(ModelHelper.java:152)
	at org.apache.camel.impl.DefaultCamelContext.loadRoutesDefinition(DefaultCamelContext.java:1031)
	at org.apache.camel.spring.boot.RoutesCollector.loadXmlRoutes(RoutesCollector.java:302)
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:161)
	... 38 more
```
**Step2**
Added below dependency
```
 <dependency>
       <groupId>xerces</groupId>
       <artifactId>xercesImpl</artifactId>
       <version>2.12.0</version>
  </dependency>


Getting same error as above.

**Comment by dsyer** [comment]
I believe `GuiceAutowireCandidateResolver` will take care of this now. That was introduced in another context, but it works for this use case (but not for `ApplicationContext.getBean(Benz.class)`), so I think that provides parity with Guice native bindings.
